# Generated by Django 3.2 on 2021-12-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocInfo',
            fields=[
                ('Name', models.CharField(max_length=200)),
                ('PlaceId', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Rating', models.FloatField()),
                ('StreetAddress', models.CharField(max_length=200)),
            ],
        ),
    ]
